spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  application.name: proverb-of-the-day

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 3500

---

spring:
  profiles: prod
  datasource:
    url: jdbc:h2:file:~/h2/proverb-data
#    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3600
